name: "[MacOS] Build TF Examples"

on:
  push:

jobs:
  macOS:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout The-Forge
      uses: actions/checkout@v3
      with:
        path: The-Forge

    - name: Checkout Custom-Middleware
      uses: actions/checkout@v3
      with:
        path: Custom-Middleware
        repository: ConfettiFX/Custom-Middleware
        ref: ${{ github.ref_name }}  # Checkout the Custom-Middleware branch with the same name as the The-Forge branch we're building

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Build
      working-directory: The-Forge
      run: python -u ./CI/PyBuild.py --preserveworkingdir --prebuild --printbuildoutput --skipioscodesigning
